### PR TITLE
Added code to calculate total score of testing code at end.

### PR DESCRIPTION
**Pull request by WingofaGriffin**
Adds a final line at the end to tell them the total score they got instead of having to add it all up themselves.

### CODE REVIEW

**Comment by kljensen** [comment]
Thanks @WingofaGriffin . Could you change this slightly to turn on only when a flag is passed on the command line, like `--verbose`? Otherwise, the output will not be valid JSON.

**Comment by WingofaGriffin** [comment]
@kljensen I added the flag in under --final-score. Did some basic testing and it seems to work as intended.

**Comment by WingofaGriffin** [comment]
@kljensen I also fixed some edgecases we had for bad urls in this commit that a student had trouble with

**Comment by WingofaGriffin** [comment]
It was the most efficient way of allowing both `http` and `https` I could find, as the other else statements in the code already check to see if the url routes correctly. It's just a wildcard statement. `dash.ga.co` has no SSL encryption as it is a url shortener, so it has no `https` option.

**Comment by kljensen** [comment]
Does startswith support globbing like that??

**Comment by WingofaGriffin** [comment]
Yes, I tested it out myself. If you want to branch it and test for yourself go ahead. I believe it is a universal JS thing with strings.

**Pull request merged**
